// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikazuqhukvtdorscoads.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrYXp1cWh1a3Z0ZG9yc2NvYWRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NzkyNDcsImV4cCI6MjA1ODE1NTI0N30.vUGlOpB5iwTGPkXYh2LsIiYXm8_t9NX19T9-0OtJREk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);